[package]
name = "a2048"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "tui"
path = "src/tui.rs"

[dependencies]
slint = {version = "1.8.0", features = ["backend-android-activity-06"] }
rand = "0.8.4"
